// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCHG2-JwlwFoNkHyEhdrSJlJEVBRgp2g',
    appId: '1:100406512452:web:c524e32f8662fdf2ed2511',
    messagingSenderId: '100406512452',
    projectId: 'chatapp-d7e82',
    authDomain: 'chatapp-d7e82.firebaseapp.com',
    storageBucket: 'chatapp-d7e82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqSvTxqNGeTJYxCKE3H1m9MCnOqT80R0',
    appId: '1:100406512452:android:4d913a4a22ff4cceed2511',
    messagingSenderId: '100406512452',
    projectId: 'chatapp-d7e82',
    storageBucket: 'chatapp-d7e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-KCIpkwep5iv3dCMbPiO_lZ0TKcIiqA',
    appId: '1:100406512452:ios:f7fd082f4e3c3a38ed2511',
    messagingSenderId: '100406512452',
    projectId: 'chatapp-d7e82',
    storageBucket: 'chatapp-d7e82.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-KCIpkwep5iv3dCMbPiO_lZ0TKcIiqA',
    appId: '1:100406512452:ios:f7fd082f4e3c3a38ed2511',
    messagingSenderId: '100406512452',
    projectId: 'chatapp-d7e82',
    storageBucket: 'chatapp-d7e82.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpCHG2-JwlwFoNkHyEhdrSJlJEVBRgp2g',
    appId: '1:100406512452:web:6819b5fe9c9f1dc2ed2511',
    messagingSenderId: '100406512452',
    projectId: 'chatapp-d7e82',
    authDomain: 'chatapp-d7e82.firebaseapp.com',
    storageBucket: 'chatapp-d7e82.appspot.com',
  );
}
